const { makeErrorMappingProxy } = require('@aragon/contract-helpers-test')

module.exports = makeErrorMappingProxy({
  // aragonOS errors
  APP_AUTH_FAILED: 'APP_AUTH_FAILED',
  INIT_ALREADY_INITIALIZED: 'INIT_ALREADY_INITIALIZED',
  INIT_NOT_INITIALIZED: 'INIT_NOT_INITIALIZED',
  RECOVER_DISALLOWED: 'RECOVER_DISALLOWED',

  // Vault errors
  VAULT_DATA_NON_ZERO: 'VAULT_DATA_NON_ZERO',
  VAULT_NOT_DEPOSITABLE: 'VAULT_NOT_DEPOSITABLE',
  VAULT_DEPOSIT_VALUE_ZERO: 'VAULT_DEPOSIT_VALUE_ZERO',
  VAULT_TRANSFER_VALUE_ZERO: 'VAULT_TRANSFER_VALUE_ZERO',
  VAULT_SEND_REVERTED: 'VAULT_SEND_REVERTED',
  VAULT_VALUE_MISMATCH: 'VAULT_VALUE_MISMATCH',
  VAULT_TOKEN_TRANSFER_FROM_REVERT: 'VAULT_TOKEN_TRANSFER_FROM_REVERT',
  VAULT_TOKEN_TRANSFER_REVERTED: 'VAULT_TOKEN_TRANSFER_REVERTED'
})
