'app: agent': ['/apps/agent']
'app: finance': ['/apps/finance']
'app: token manager': ['/apps/token-manager']
'app: vault': ['/apps/vault']
'app: voting': ['/apps/voting']
'component: contract': ['*.sol']
'component: frontend': [
  '/apps/agent/app',
  '/apps/finance/app',
  '/apps/token-manager/app',
  '/apps/vault/app',
  '/apps/voting/app'
]
