# Configuration for https://probot.github.io/apps/welcome

newIssueWelcomeComment: >
  Thanks for opening your first issue in the Aragon apps repo! Someone will circle back soon ⚡

newPRWelcomeComment: >
  Thanks for opening this pull request! Someone will review it soon 🔍

firstPRMergeComment: >
  Congrats on merging your first pull request! Aragon is proud of you 🦅

  ![Eagle gif](https://media.giphy.com/media/SLD8eKFPuUDuw/200w_d.gif)
