module.exports = {
  SETTING_CHANGED: 'SettingChanged',
  ACTION_SCHEDULED: 'ActionScheduled',
  ACTION_CHALLENGED: 'ActionChallenged',
  ACTION_SETTLED: 'ActionSettled',
  ACTION_DISPUTED: 'ActionDisputed',
  ACTION_ACCEPTED: 'ActionAccepted',
  ACTION_VOIDED: 'ActionVoided',
  ACTION_REJECTED: 'ActionRejected',
  ACTION_CANCELLED: 'ActionCancelled',
  ACTION_EXECUTED: 'ActionExecuted',
  BALANCE_STAKED: 'BalanceStaked',
  BALANCE_UNSTAKED: 'BalanceUnstaked',
  BALANCE_LOCKED: 'BalanceLocked',
  BALANCE_UNLOCKED: 'BalanceUnlocked',
  BALANCE_CHALLENGED: 'BalanceChallenged',
  BALANCE_UNCHALLENGED: 'BalanceUnchallenged',
  BALANCE_SLAHED: 'BalanceSlashed',
}
