export const VOTE_STATUS_ONGOING = Symbol('VOTE_STATUS_ONGOING')
export const VOTE_STATUS_SUCCESSFUL = Symbol('VOTE_STATUS_SUCCESSFUL')
export const VOTE_STATUS_FAILED = Symbol('VOTE_STATUS_FAILED')
export const VOTE_STATUS_EXECUTED = Symbol('VOTE_STATUS_EXECUTED')
