//
// Event Types
//

const INITIALIZATION_TRIGGER = Symbol('INITIALIZATION_TRIGGER')

// User account
const ACCOUNT_CHANGED = Symbol('ACCOUNT_CHANGED')

// Payroll app
const ADD_ALLOWED_TOKEN = Symbol('ADD_ALLOWED_TOKEN')
const ADD_EMPLOYEE = Symbol('ADD_EMPLOYEE')
const ADD_EMPLOYEE_ACCRUED_VALUE = Symbol('ADD_EMPLOYEE_ACCRUED_VALUE')
const CHANGE_EMPLOYEE_ADDRESS = Symbol('CHANGE_EMPLOYEE_ADDRESS')
const DETERMINE_ALLOCATION = Symbol('DETERMINE_ALLOCATION')
const SET_EMPLOYEE_SALARY = Symbol('SET_EMPLOYEE_SALARY')
const SEND_PAYROLL = Symbol('SEND_PAYROLL')
const SET_PRICE_FEED = Symbol('SET_PRICE_FEED')
const SET_RATE_EXPIRY_TIME = Symbol('SET_RATE_EXPIRY_TIME')
const TERMINATE_EMPLOYEE = Symbol('TERMINATE_EMPLOYEE')

export default {
  'Init': INITIALIZATION_TRIGGER,

  'AccountChange': ACCOUNT_CHANGED,

  'AddAllowedToken': ADD_ALLOWED_TOKEN,
  'AddEmployee': ADD_EMPLOYEE,
  'AddEmployeeAccruedValue': ADD_EMPLOYEE_ACCRUED_VALUE,
  'ChangeAddressByEmployee': CHANGE_EMPLOYEE_ADDRESS,
  'DetermineAllocation': DETERMINE_ALLOCATION,
  'SetEmployeeSalary': SET_EMPLOYEE_SALARY,
  'SendPayroll': SEND_PAYROLL,
  'SetPriceFeed': SET_PRICE_FEED,
  'SetRateExpiryTime': SET_RATE_EXPIRY_TIME,
  'TerminateEmployee': TERMINATE_EMPLOYEE
}
