name: contracts:token-manager

on:
  push:
    paths:
    # Select the root folder and TokenManager's smart contracts
    - '*'
    - 'apps/token-manager/*'
    - '!apps/token-manager/app'

defaults:
  run:
    working-directory: 'apps/token-manager'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: yarn install
      run: yarn install --frozen-lockfile
      # Bootstrap from root
      working-directory: './'
    - name: lint
      run: yarn run lint
    - name: test
      run: yarn run test
    - name: coverage
      run: yarn run coverage
env:
  CI: true
