name: frontend:agent

on:
  push:
    paths:
    # Select the root folder and Agent's frontend
    - '*'
    - 'apps/agent/app'

defaults:
  run:
    working-directory: 'apps/agent/app'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: lint
      run: yarn run lint
    - name: test
      run: yarn run test
env:
  CI: true
