name: Test Release

on:
  pull_request_target:
    types: [closed]

env:
  POSSIBLE_NETWORKS: "mainnet rinkeby mumbai matic arbitrum harmony harmonyTest "

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.labels.*.name
    steps:
      - run: echo Check labels is not empty and pull is merged
  buildMatrix:
    needs: [checkLabels]
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.matrix.outputs.labels }}
      networks: ${{ steps.networks.outputs.networks }}
      valid: ${{ steps.matrix.outputs.valid }}
    steps:
      - name: Get Networks
        id: networks
        env:
          PULL_LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          NETWORKS=""
          for LABEL in $(echo $PULL_LABELS | jq -r '.[].name'); do
            if [[ $POSSIBLE_NETWORKS =~ (^|[[:space:]])$LABEL($|[[:space:]]) ]]; then
              NETWORKS+=" $LABEL"
            fi
          done
          echo "::set-output name=networks::$(jq -c -n --arg v "${NETWORKS:1}" '$v | split(" ")')"
      - name: Build Matrix
        id: matrix
        env:
          PULL_LABELS: ${{ toJson(github.event.pull_request.labels) }}
          NETWORKS: ${{ steps.networks.outputs.networks }}
        # loop through all labels and prepare matrix to run in the next job
        run: |
          LABELS=()
          for LABEL in $(echo $PULL_LABELS | jq -r '.[].name'); do 
            APP=$(cut -d":" -f1 <<< $LABEL)
            LEVEL=$(cut -d":" -f2 <<< $LABEL)
            if [ $LEVEL = 'minor' ] || [ $LEVEL = 'major' ] || [ $LEVEL = 'patch' ]; then 
              for NETWORK in $(echo $NETWORKS | jq -r '.[]'); do
                LABELS[${#LABELS[@]}]="{\"app\": \"$APP\", \"level\": \"$LEVEL\", \"network\": \"$NETWORK\"}"
              done
            fi
          done

          if [ ${#LABELS[@]} -eq 0 ]; then
            echo "::set-output name=valid::false"
          else
            JSON="["
            for i in "${LABELS[@]}"; do
              JSON+="$i,"
            done
            JSON="${JSON::-1}]"
            echo "::set-output name=labels::{\"include\":$JSON}"
            echo "::set-output name=valid::true"
          fi
  release:
    needs: [buildMatrix]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && needs.buildMatrix.outputs.valid == 'true'
    strategy:
      matrix: ${{ fromJson(needs.buildMatrix.outputs.labels) }}
      fail-fast: false
    environment: ${{ matrix.network }}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: setup ipfs
        uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
      - name: Configure aragon cli 
        run: |
          mkdir -p ~/.aragon
          echo ${{ secrets.ARAGON_CLI_JSON }} >> ~/.aragon/${{ matrix.network }}_key.json
      - name: Install npm packages
        run: yarn
      - name: build, publish and package
        id: build
        run: | 
          cd apps/voting
          yarn --ignore-engines --dev
          if [[ -d app ]]; then
            yarn build
          fi
      - name: publish
        id: publish
        run:  |
          cd apps/voting
          PUBLISH_MESSAGE=$(npx hardhat publish patch --skip-validation --dry-run --network mumbai)
          echo "publish message"
          echo "$PUBLISH_MESSAGE" | grep 'ContentURI'
          echo "$PUBLISH_MESSAGE" | grep 'new version'
          echo $PUBLISH_MESSAGE | grep 'new version' | awk '{ split($0,a," "); print a[6] }'
          echo $PUBLISH_MESSAGE | grep 'ContentURI' | awk '{ split($0,a," "); print a[4] }'
          echo "...."
          echo "::set-output name=cid::$(echo $PUBLISH_MESSAGE | grep 'ContentURI' | awk '{ split($0,a," "); print a[4] }')"
          echo "::set-output name=version::$(echo $PUBLISH_MESSAGE | grep 'new version' | awk '{ split($0,a," "); print a[6] }')"
      - name: create tag
        env:
          TAG_NAME: "test-tag-${{ steps.publish.outputs.version }}-${{ steps.publish.outputs.cid }}"
        run: |
          echo "tag: $TAG_NAME"