name: Test Hardhat

on:
  push:
    branches:
      - test-hardhat-2 

env:
  POSSIBLE_NETWORKS: "mainnet rinkeby mumbai matic harmony harmonyTest "

jobs:
  runHardhat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'test-hardhat-2'
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: build, publish and package
        id: build
        run: | 
          cd apps/test-hardhat
          yarn --ignore-engines --dev
          if [[ -d app ]]; then
            yarn build
          fi
      - name: publish
        id: publish
        run: |
          cd apps/test-hardhat
          echo ====== ls node-modules
          ls node_modules
          npx hardhat help
